"""empty message

Revision ID: 4d63e9a96a7c
Revises: 816f26a126bf
Create Date: 2022-10-04 23:05:03.007664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d63e9a96a7c'
down_revision = '816f26a126bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuario', ['mail'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    # ### end Alembic commands ###
